command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
entity: ahoj
method: random
name: MSG
program: algorithms/msg.py
project: eval

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  dataset:
    values:
      - halfcheetah-medium-v2
  algorithm:
    value: msg
  num_updates:
    value: 1_000_000
  eval_interval:
    value: 2500
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  wandb_project:
    value: eval
  wandb_team:
    value: ahoj
  wandb_group:
    value: debug

  # --- Generic optimization ---
  lr:
    values: [1e-4, 3e-4]
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005

  # --- SAC-N ---
  num_critics:
    value: 10

  # --- MSG ---
  cql_min_q_weight: 
    values : [0.0, 0.1, 0.3]
  actor_lcb_coef : 
    values : [2.0, 4.0, 8.0]
