command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
entity: ensemble_offline_rl
method: random
name: msg
program: algorithms/unified.py
project: ensemble_offline_rl


parameters:
  # --- Experiment ---
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  dataset-source:
    value: d4rl
  dataset-name:
    values: 
      - hopper-medium-v2
  algorithm:
    value: msg
  num_updates:
    value : 1_000_000
  eval_interval:
    value: 10_000
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  checkpoint_dir:
    value: "./checkpoints/msg"
  checkpoint:
    value: true
  # --- Generic optimization ---
  lr:
    value: 3e-4
  actor_lr:
    value: 1e-4
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005


  # --- MSG specific ---
  critic_regularizer:
    value: "msg"

  pi_operator:
    value: "lcb"

  beta_id:
    value: 0.0

  actor_lcb_penalty:
    values: [4.0, 8.0]
  critic_lagrangian:
    values: [0, 0.1, 0.5, 1.0, 2.0, 4.0, 8.0]
  num_critics:
    values: [10, 30]
  
