command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
entity: ahoj
method: grid
name: CQL
program: minari/cql.py
project: square-cql

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1]
  dataset:
    values: [square-reach/horizon-10-v0, square-reach/horizon-20-v0, square-reach/horizon-50-v0]
  algorithm:
    value: cql
  num_updates:
    #values: [200_000, 500_000]
    value : 300_000
  eval_interval:
    value: 2500
  eval_workers:
    value: 1
  eval_final_episodes:
    value: 0

  # --- Logging ---
  log:
    value: true
  wandb_project:
    value: square-cql
  wandb_team:
    value: ahoj
  wandb_group:
    value: debug

  # --- Generic optimization ---
  lr:
    value: 3e-4 
  batch_size:
    value: 256
  gamma:
    value: 0.999
  polyak_step_size:
    value: 0.005

  # --- SAC-N ---
  num_critics:
    value: 2

  # --- CQL ---
  actor_lr:
    value: 3e-4
  cql_temperature:
    value: 1.0
  cql_min_q_weight:
    values: [0.0, 5.0, 10.0]
