command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
entity: ahoj
method: grid
name: MSG
program: minari/msg.py
project: square-msg

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1]
  dataset:
    values: [square-reach/horizon-10-v0, square-reach/horizon-20-v0, square-reach/horizon-50-v0]
  algorithm:
    value: msg
  num_updates:
    values: [50_000, 100_000]
  eval_interval:
    value: 2500
  eval_workers:
    value: 1
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  wandb_project:
    value: square-msg
  wandb_team:
    value: ahoj
  wandb_group:
    value: debug

  # --- Generic optimization ---
  lr:
    value: [3e-4]
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005

  # --- SAC-N ---
  num_critics:
    value: [10, 30]

  # --- MSG ---
  cql_min_q_weight: 
    values : [0.0, 0.1, 0.3]
  actor_lcb_coef : 
    values : [2.0, 4.0, 8.0]
